apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stpl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stpl
    spec:
      containers:
      - name: stpl
        image: docker.io/luebken/stpl
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
        env:
          - name: REDIS_URL
            value: redis.mdl.svc:6379
          - name: LIBRARIES_IO_API_KEY
            value: <TODO_INSERT>